[package]
name = "pywr-next"
version = "0.1.0"
authors = ["James Tomlinson <tomo.bbe@gmail.com>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.97"
thiserror = "1.0.25"
chrono = "0.4.19"
ndarray = "0.15.3"
numpy = "0.14.1"
float-cmp = "0.8.0"
hdf5 = { version="0.8.1" }
clp-sys = { path = "./clp-sys" }
wasmer = "2.0.0"


[dependencies.pyo3]
version = "0.14.1"

[dev-dependencies]
tempdir = "0.3.7"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[lib]
name = "pywr"
crate-type = ["cdylib"]

[package.metadata.maturin]
requires-dist = ["pydantic"]

[workspace]
members = [
    "clp-sys",
]
exclude = [
    "tests/models/simple-wasm/simple-wasm-parameter"
]
