[tool.poetry]
name = "pywr"
version = "2.0.0beta"
description = ""
authors = ["James Tomlinson <tomo.bbe@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.2.0"
polars = "^0.20.5"
pyarrow = "^15.0.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
maturin = ">=1.0,<2.0"
pytest = "^7.4.4"
h5py = "^3.10.0"


[build-system]
requires = ["poetry-core", "maturin>=1.0,<2.0"]
build-backend = "maturin"


[tool.maturin]
manifest-path = "pywr-python/Cargo.toml"
python-source = "pywr-python"
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module"]
